# Generated by Django 5.0.14 on 2026-04-29 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnalyticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('new_organizers', models.PositiveIntegerField(default=0)),
                ('events_published', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('confirmed_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'platform_analytics_daily',
            },
        ),
        migrations.CreateModel(
            name='EventAnalyticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('checkout_starts', models.PositiveIntegerField(default=0)),
                ('orders_created', models.PositiveIntegerField(default=0)),
                ('orders_confirmed', models.PositiveIntegerField(default=0)),
                ('tickets_sold', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('refunds_count', models.PositiveIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('check_ins', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_daily', to='events.event')),
            ],
            options={
                'db_table': 'event_analytics_daily',
                'indexes': [models.Index(fields=['event'], name='event_analy_event_i_91d018_idx')],
                'unique_together': {('event', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('medium', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_sources', to='events.event')),
            ],
            options={
                'db_table': 'traffic_sources',
                'unique_together': {('event', 'source', 'date')},
            },
        ),
    ]
