# Generated by Django 5.0.14 on 2026-04-29 12:10

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField(blank=True, null=True)),
                ('variables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='organizers.organizer')),
            ],
            options={
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('TICKET_TRANSFERRED', 'Ticket Transferred'), ('EVENT_REMINDER', 'Event Reminder'), ('EVENT_CANCELLED', 'Event Cancelled'), ('EVENT_POSTPONED', 'Event Postponed'), ('EVENT_UPDATED', 'Event Updated'), ('PAYOUT_PROCESSED', 'Payout Processed'), ('PAYOUT_FAILED', 'Payout Failed'), ('NEW_ORDER', 'New Order'), ('DAILY_SUMMARY', 'Daily Summary'), ('PROMO_CODE', 'Promo Code'), ('SYSTEM_ALERT', 'System Alert'), ('REFUND_PROCESSED', 'Refund Processed'), ('CHECKIN_SUMMARY', 'Checkin Summary')], max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'Sms'), ('WHATSAPP', 'Whatsapp'), ('IN_APP', 'In App'), ('PUSH', 'Push')], max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=15)),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('fail_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_e78525_idx'), models.Index(fields=['status'], name='notificatio_status_fce6f5_idx'), models.Index(fields=['notif_type'], name='notificatio_notif_t_d57951_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(max_length=30)),
                ('channel', models.CharField(max_length=15)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
                'unique_together': {('user', 'notif_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth_key', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
