# Generated by Django 4.2.30 on 2026-06-28 19:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_organizer_auto_payout_days_after_and_more'),
        ('events', '0002_event_checkin_access_code_checkinstaff'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('channel', models.CharField(default='EMAIL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_templates', to='organizers.organizer')),
            ],
            options={
                'db_table': 'organizer_templates',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_announcements', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='organizers.organizer')),
            ],
            options={
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(max_length=100)),
                ('trigger_label', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('offset_hours', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='organizers.organizer')),
            ],
            options={
                'db_table': 'automations',
                'unique_together': {('organizer', 'trigger', 'channel')},
            },
        ),
    ]
