# Generated by Django 5.0.14 on 2026-06-26 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_email_idx_users_email_4b85f2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_payout_profiles',
            },
        ),
    ]
