# Generated by Django 4.2.30 on 2026-06-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpayoutprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayoutprofile',
            name='mpesa_phone',
        ),
        migrations.AddField(
            model_name='userpayoutprofile',
            name='paystack_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userpayoutprofile',
            name='paystack_bank_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userpayoutprofile',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
