# Generated by Django 5.0.14 on 2026-04-29 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('organizers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('access_code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_sessions', to='events.event')),
            ],
            options={
                'db_table': 'checkin_sessions',
            },
        ),
        migrations.CreateModel(
            name='GateStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_assignments', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='checkin.checkinsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gate_staff_assignments',
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_token', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('ALREADY_USED', 'Already Used'), ('CANCELLED', 'Cancelled'), ('EVENT_NOT_STARTED', 'Event Not Started'), ('EVENT_ENDED', 'Event Ended')], max_length=20)),
                ('gate', models.CharField(blank=True, max_length=100)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='checkin.checkinsession')),
            ],
            options={
                'db_table': 'scan_logs',
            },
        ),
    ]
