# Generated by Django 5.0.14 on 2026-04-29 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkin', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='checkinsession',
            index=models.Index(fields=['event'], name='checkin_ses_event_i_03c18b_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinsession',
            index=models.Index(fields=['access_code'], name='checkin_ses_access__459acc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gatestaffassignment',
            unique_together={('session', 'user')},
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['session'], name='scan_logs_session_6367be_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['ticket'], name='scan_logs_ticket__d48e91_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['scanned_at'], name='scan_logs_scanned_bdb491_idx'),
        ),
    ]
