# Generated by Django 5.0.14 on 2026-04-29 11:40

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon_url', models.URLField(blank=True, max_length=300)),
                ('color_hex', models.CharField(default='#f59e0b', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('promo_video_url', models.URLField(blank=True, max_length=500)),
                ('event_type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='PHYSICAL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed'), ('COMPLETED', 'Completed'), ('UNDER_REVIEW', 'Under Review')], default='DRAFT', max_length=15)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('doors_open_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('is_recurring', models.BooleanField(default=False)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_address', models.CharField(blank=True, max_length=300)),
                ('venue_city', models.CharField(blank=True, max_length=100)),
                ('venue_county', models.CharField(blank=True, max_length=100)),
                ('venue_country', models.CharField(default='KE', max_length=3)),
                ('venue_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('venue_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('venue_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('venue_map_url', models.URLField(blank=True, max_length=500)),
                ('online_url', models.URLField(blank=True, max_length=500)),
                ('online_password', models.CharField(blank=True, max_length=100)),
                ('online_platform', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('youtube', 'Youtube'), ('custom', 'Custom')], max_length=20)),
                ('age_restriction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dress_code', models.CharField(blank=True, max_length=200)),
                ('entry_rules', models.TextField(blank=True)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('max_per_order', models.PositiveSmallIntegerField(default=10)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('postponed_to', models.DateTimeField(blank=True, null=True)),
                ('postpone_note', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizers.organizer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer')),
            ],
            options={
                'db_table': 'event_announcements',
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='events.event')),
            ],
            options={
                'db_table': 'event_gallery',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('body', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_reviews',
            },
        ),
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField()),
                ('status', models.CharField(default='SCHEDULED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event')),
            ],
            options={
                'db_table': 'recurring_events',
            },
        ),
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_event', models.PositiveSmallIntegerField()),
                ('refund_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_policies', to='events.event')),
            ],
            options={
                'db_table': 'refund_policies',
                'ordering': ['-days_before_event'],
            },
        ),
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_events',
            },
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('max_per_order', models.PositiveSmallIntegerField(default=10)),
                ('min_per_order', models.PositiveSmallIntegerField(default=1)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('HIDDEN', 'Hidden'), ('INVITE_ONLY', 'Invite Only')], default='PUBLIC', max_length=15)),
                ('sale_starts_at', models.DateTimeField(blank=True, null=True)),
                ('sale_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=False)),
                ('is_group_tier', models.BooleanField(default=False)),
                ('group_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('perks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='events.event')),
            ],
            options={
                'db_table': 'ticket_tiers',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='events_organiz_1c7a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_status_8890b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at'], name='events_starts__f39f74_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_slug_930801_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='events_categor_fd16be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventreview',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='savedevent',
            unique_together={('user', 'event')},
        ),
        migrations.AddIndex(
            model_name='tickettier',
            index=models.Index(fields=['event'], name='ticket_tier_event_i_8c42c4_idx'),
        ),
    ]
