# Generated by Django 4.2.30 on 2026-06-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_checkin_access_code_checkinstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_fee_flat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fee_absorbed_by',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('organizer', 'Organizer')], default='buyer', max_length=20),
        ),
    ]
