# Generated by Django 4.2.30 on 2026-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_custom_fee_flat_event_custom_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_terms',
            field=models.TextField(blank=True),
        ),
    ]
