# Generated by Django 4.2.30 on 2026-06-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_custom_fee_flat_event_custom_fee_percent_and_more'),
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='applicable_tiers',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='events.tickettier'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='code_type',
            field=models.CharField(choices=[('PROMO', 'Promo'), ('REFERRAL', 'Referral'), ('BULK', 'Bulk')], default='PROMO', max_length=15),
        ),
        migrations.AddField(
            model_name='promocode',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='events.event'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='referral_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
