# Generated by Django 4.2.30 on 2026-06-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='integrity_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
