# Generated by Django 4.2.30 on 2026-06-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_integrity_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
