# Generated by Django 4.2.30 on 2026-06-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('report_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('USER_GROWTH', 'User Growth'), ('EVENT_PERFORMANCE', 'Event Performance'), ('LIABILITIES', 'Liabilities')], max_length=30)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'report_subscriptions',
                'unique_together': {('email', 'report_type', 'frequency')},
            },
        ),
    ]
