# Generated by Django 4.2.30 on 2026-06-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_reportsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee', models.CharField(default='5% of ticket face value', max_length=200)),
                ('payment_processing_mpesa', models.CharField(default='1.5% + KES 20 per transaction', max_length=200)),
                ('payment_processing_card', models.CharField(default='2.9% + KES 30 per transaction', max_length=200)),
                ('bank_transfer_fee', models.CharField(default='KES 50 flat per payout', max_length=200)),
                ('free_events_fee', models.CharField(default='No charge', max_length=200)),
                ('payout_schedule', models.CharField(default='5-7 business days after event date', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Fee Setting',
                'db_table': 'platform_fee_settings',
            },
        ),
    ]
