# Generated by Django 5.0.14 on 2026-04-29 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('banner_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, max_length=300)),
                ('facebook_url', models.URLField(blank=True, max_length=300)),
                ('twitter_url', models.URLField(blank=True, max_length=300)),
                ('instagram_url', models.URLField(blank=True, max_length=300)),
                ('youtube_url', models.URLField(blank=True, max_length=300)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('ngo', 'Ngo')], default='individual', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_pin', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('VERIFIED', 'Verified'), ('PREMIUM', 'Premium')], default='BASIC', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('custom_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('custom_fee_flat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fee_absorbed_by', models.CharField(choices=[('buyer', 'Buyer'), ('organizer', 'Organizer')], default='buyer', max_length=20)),
                ('payout_method', models.CharField(choices=[('MPESA', 'Mpesa'), ('BANK_TRANSFER', 'Bank Transfer')], default='MPESA', max_length=20)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('kyc_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NOT_SUBMITTED', max_length=20)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_rejection_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizers',
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('national_id', 'National Id'), ('passport', 'Passport'), ('reg_cert', 'Reg Cert'), ('kra_pin', 'Kra Pin')], max_length=20)),
                ('file_url', models.URLField(max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='organizers.organizer')),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
        migrations.CreateModel(
            name='OrganizerFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='organizers.organizer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_organizers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizer_followers',
            },
        ),
        migrations.AddIndex(
            model_name='organizer',
            index=models.Index(fields=['slug'], name='organizers_slug_bed647_idx'),
        ),
        migrations.AddIndex(
            model_name='organizer',
            index=models.Index(fields=['status'], name='organizers_status_bf2888_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizerfollower',
            unique_together={('organizer', 'user')},
        ),
    ]
