# Generated by Django 4.2.30 on 2026-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='fee_agreement_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizer',
            name='fee_agreement_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
