# Generated by Django 4.2.30 on 2026-06-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_organizer_fee_agreement_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='auto_payout_days_after',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='organizer',
            name='payout_schedule',
            field=models.CharField(choices=[('INSTANT', 'Instant'), ('POST_EVENT', 'Post Event'), ('ON_DEMAND', 'On Demand')], default='ON_DEMAND', max_length=20),
        ),
    ]
