# Generated by Django 4.2.30 on 2026-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_organizer_auto_payout_days_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='contact_address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
