# Generated by Django 5.0.14 on 2026-04-29 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('MPESA_STK', 'Mpesa Stk'), ('MPESA_PAYBILL', 'Mpesa Paybill'), ('CARD_STRIPE', 'Card Stripe'), ('CARD_FLUTTERWAVE', 'Card Flutterwave'), ('BANK_TRANSFER', 'Bank Transfer'), ('FREE', 'Free'), ('USSD', 'Ussd')], max_length=25)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mpesa_merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('mpesa_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100)),
                ('flutterwave_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('bank_confirmed_by', models.CharField(blank=True, max_length=200)),
                ('bank_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['order'], name='payments_order_i_b32b33_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['mpesa_checkout_request_id'], name='payments_mpesa_c_ccf63f_idx')],
            },
        ),
    ]
