# Generated by Django 4.2.30 on 2026-06-25 11:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('organizers', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('daraja', 'Daraja'), ('paystack', 'Paystack')], max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('raw_payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('daraja', 'Daraja (M-Pesa)'), ('paystack', 'Paystack')], max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('organizer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_gateway_response', models.JSONField(default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gateway', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('swept_to_account', models.BooleanField(default=False)),
                ('swept_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_revenue', to='payments.tickettransaction')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerPayoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], default='mpesa', max_length=10)),
                ('mpesa_phone', models.CharField(blank=True, max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch_code', models.CharField(blank=True, max_length=20)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=60)),
                ('payout_status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending_verification', max_length=30)),
                ('verification_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_profile', to='organizers.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('permanently_failed', 'Permanently Failed')], default='queued', max_length=30)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('external_ref', models.CharField(blank=True, max_length=150)),
                ('raw_disbursement_response', models.JSONField(default=dict)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_payouts', to='organizers.organizer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_payouts', to='payments.tickettransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='tickettransaction',
            index=models.Index(fields=['mpesa_checkout_request_id'], name='payments_ti_mpesa_c_0473dc_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransaction',
            index=models.Index(fields=['paystack_reference'], name='payments_ti_paystac_7228fe_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransaction',
            index=models.Index(fields=['payment_status'], name='payments_ti_payment_b67ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='organizerpayout',
            index=models.Index(fields=['status'], name='payments_or_status_baae87_idx'),
        ),
        migrations.AddIndex(
            model_name='organizerpayout',
            index=models.Index(fields=['organizer', 'status'], name='payments_or_organiz_4bc362_idx'),
        ),
        migrations.AddIndex(
            model_name='organizerpayout',
            index=models.Index(fields=['next_retry_at'], name='payments_or_next_re_3c9b65_idx'),
        ),
    ]
