# Generated by Django 5.0.14 on 2026-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_webhooklog_tickettransaction_platformrevenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MPESA_STK', 'Mpesa Stk'), ('MPESA_PAYBILL', 'Mpesa Paybill'), ('CARD_STRIPE', 'Card Stripe'), ('CARD_PAYSTACK', 'Card Paystack'), ('CARD_FLUTTERWAVE', 'Card Flutterwave'), ('BANK_TRANSFER', 'Bank Transfer'), ('FREE', 'Free'), ('USSD', 'Ussd')], max_length=25),
        ),
    ]
