# Generated by Django 4.2.30 on 2026-06-28 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_resaletransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerpayout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organizerpayout',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='organizerpayout',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_payouts', to='payments.tickettransaction'),
        ),
    ]
