# Generated by Django 4.2.30 on 2026-06-23 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('attachment_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='refunds.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispute_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
