# Generated by Django 5.0.14 on 2026-04-29 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('CANCELLED', 'Cancelled'), ('TRANSFERRED', 'Transferred'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=15)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('qr_code_url', models.URLField(blank=True, max_length=500)),
                ('holder_name', models.CharField(max_length=200)),
                ('holder_email', models.EmailField(blank=True, max_length=254)),
                ('holder_phone', models.CharField(blank=True, max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_gate', models.CharField(blank=True, max_length=100)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='orders.order')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.tickettier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_phone', models.CharField(blank=True, max_length=20)),
                ('transfer_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='tickets.ticket')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_transfers',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order'], name='tickets_order_i_929c77_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user'], name='tickets_user_id_3c7de8_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['qr_token'], name='tickets_qr_toke_434761_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_status_fbbf05_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransfer',
            index=models.Index(fields=['ticket'], name='ticket_tran_ticket__880028_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransfer',
            index=models.Index(fields=['transfer_token'], name='ticket_tran_transfe_101c71_idx'),
        ),
    ]
