# Generated by Django 5.0.14 on 2026-04-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_url',
            field=models.TextField(blank=True),
        ),
    ]
