# Generated by Django 5.0.14 on 2026-06-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tickettransfer_decline_reason_declined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('CANCELLED', 'Cancelled'), ('TRANSFERRED', 'Transferred'), ('EXPIRED', 'Expired'), ('FOR_RESALE', 'For Resale')], default='ACTIVE', max_length=15),
        ),
    ]
