# Generated by Django 4.2.30 on 2026-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_resale_price_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
