# Generated by Django 5.0.14 on 2026-04-29 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('organizers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('method', models.CharField(choices=[('MPESA', 'Mpesa'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=15)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_approvals', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='organizers.organizer')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payouts',
            },
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payouts.payout')),
            ],
            options={
                'db_table': 'payout_items',
            },
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['organizer'], name='payouts_organiz_1f7cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='payouts_status_20cd29_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['payout'], name='payout_item_payout__177d83_idx'),
        ),
    ]
