# Generated by Django 4.2.30 on 2026-06-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payout',
            name='deduction_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
