from django.urls import path
from . import views

urlpatterns = [
    path("dashboard/", views.admin_dashboard),
    path("revenue-chart/", views.admin_revenue_chart),
    path("active-events/", views.admin_active_events),
    path("health/", views.admin_health),
    path("users/", views.list_users),
    path("users/create/", views.create_user),
    path("users/<uuid:user_id>/", views.admin_user_detail_crud),
    path("users/<uuid:user_id>/status/", views.update_user_status),
    path("users/<uuid:user_id>/<str:action>/", views.admin_user_action),
    path("organizers/", views.list_organizers),
    path("organizers/<int:org_id>/", views.admin_organizer_detail_crud),
    path("organizers/<int:org_id>/<str:action>/", views.admin_organizer_action),
    path("events/", views.list_all_events),
    path("events/<uuid:event_id>/", views.admin_event_detail),
    path("events/<uuid:event_id>/<str:action>/", views.admin_event_action),
    path("banner-slots/", views.list_banner_slots),
    path("banner-slots/<int:slot_id>/", views.update_banner_slot),
    path("payouts/", views.list_payouts),
    path("payouts/<str:action>/", views.bulk_payout_action),
    path("disputes/", views.list_disputes),
    path("disputes/<uuid:dispute_id>/messages/", views.dispute_messages),
    path("disputes/<uuid:dispute_id>/<str:action>/", views.dispute_action),
    path("vat-report/", views.vat_report),
    path("reconciliation/", views.reconciliation_report),
    path("reconciliation/sync/", views.reconciliation_sync),
    path("financial-kpis/", views.financial_kpis),
    path("refunds/", views.list_refunds),
    path("refunds/kpis/", views.refunds_kpis),
    path("refunds/<uuid:refund_id>/<str:action>/", views.refund_action),
    path("config/", views.platform_config),
    path("fee-settings/", views.platform_fee_settings),
    path("audit-logs/", views.audit_logs),
    path("reports/revenue/", views.report_revenue),
    path("reports/user-growth/", views.report_user_growth),
    path("reports/events/", views.report_events_performance),
    path("reports/subscriptions/", views.report_subscriptions),
    path("reports/liabilities/", views.report_liabilities),
    path("categories/", views.admin_categories),
    path("categories/<int:cat_id>/", views.admin_category_detail),
]
